### PR TITLE
fullscreen triangle optimization

### PR DESCRIPTION
**Pull request by TomHsiao1260**
Seems using only one fullscreen triangle would have some performance gains. Does it also apply to our situation?
Learn more: https://github.com/mrdoob/three.js/pull/21358

### CODE REVIEW

**Comment by torinmb** [comment]
This is a great recommendation for the minimal renderer! For the three.js plugin, I don't think it'd make sense because people might want to be able to include their shaders w/ other geometry, but in this context it fits really well.

We were hoping to add mouse controls to the minimal renderer at some point to have similar functionality to OrbitControlls in Three.js. Not sure if switching this to a full-screen triangle rules out that option, but I guess you can always make virtual camera controls within the shader. What are your thoughts @PWhiddy

**Comment by TomHsiao1260** [comment]
That's sounds interesting, glad to know it. I also have a similar idea during reading the `targets/threeJS` and `targets/minimalRenderer` solution. If it may be difficult to integrate them in the future, feel free to close this PR. Thanks!

**Comment by PWhiddy** [comment]
This seems like a fine change to me!
Tests seemed to pass fine, @TomHsiao1260 did you also check the rendering looks the same? 
Quickest way to check is if you run `yarn/npm test` locally, some images will be rendered to the folder `test/out`. If those look normal happy to merge :)

**Comment by TomHsiao1260** [comment]
Hi, after comparing them, they're mostly the same except for two of them may be different because of noise. Not sure if this is normal. Here's the different:

looper.png
looper
looper

rotateBoxes.png
rotateBoxes
rotateBoxes

**Comment by PWhiddy** [comment]
That looks fine to me, I'm guessing they just show up different because they are animated with time and the page loads/screenshot happens at slightly different times on each run. 
Thanks!

**Pull request merged**
