### PR TITLE
Proposal for create sculptures w/ pre-generated GLSL

### PR DESCRIPTION
**Pull request by torinmb**
ran local test + test w/ three.js

### CODE REVIEW

**Comment by torinmb** [comment]
I tacked on an extra param for createSculp where you can pass in the whole generated object. For the minimal rendered i added a whole other function. both expect the dictionary containing the frag, vert, uniforms etc.

**Comment by PWhiddy** [comment]
what is the use case for this?

**Comment by torinmb** [comment]
This is so that we can pre-generate the glsl + uniform description at build time and pass it along to have it rendered at runtime

**Comment by torinmb** [comment]
I have a working example using babel-plugin-preval that allows us to call what ever js code we want a build time as the code is being compiled. the problem is that we don't have any functions available right now that allow us to easily pass along the generated GLSL

**Pull request merged**
